### ISSUE TITLE
"Feature file already contains a scenario with name" Error

### ISSUE THREAD

**Issue by schulz3000** [deepstreamIO/deepstream.io-client-specs#3]
I got the error "Feature file already contains a scenario with name" for a lot of scenarios when using specflow and Visual Studio with provided feature files.

Steps to reproduce:
- Install specflow Visual Studio integration like described on specflow.org -> Get started
- create new UnitTest project
- add SpecFlow package from nuget
- add connecting.feature file from this repo
- generate step definitions like described on specflow.org -> Get started
- build project and run tests
  Result: project is building and tests running with warning because they are not implemented right now.
- adding the rest of the feature files from this repo and generate step positions for them
- build project
  Result: described errors appear

![deepstream_specflow_duplicated_scenario](https://cloud.githubusercontent.com/assets/1812705/13788835/af25f0c2-eae1-11e5-94ec-ac93b83deb4a.PNG)

/cc @yasserf

**Comment by yasserf** [comment]
Thanks! We'll reword them so that they are unique, guessing specflow implementation is stricter that of the js parser.

**Comment by yasserf** [comment]
Updated specs accordingly, I have to admit I didn't run them because I don't have any of the ;Net environment running, so I apologize for that!

**Comment by schulz3000** [comment]
No success here.
For example these two scenarios still have the same name
https://github.com/deepstreamIO/deepstream.io-client-specs/blob/master/features/rpc/rpc-connection.feature#L6
https://github.com/deepstreamIO/deepstream.io-client-specs/blob/master/features/events/events-connection.feature#L8

**Comment by schulz3000** [comment]
worked
Only one other small problem occur because of duplicated naming of features. Created a PR for it. #4

**Comment by yasserf** [comment]
Awesome, thanks!
